site_name: oa-configurator
site_description: A tool to generate configuration files for OMOP data model database and logging configuration focused on omop-alchemy.
site_url: https://AustralianCancerDataNetwork.github.io/oa-configurator/
repo_url: https://github.com/AustralianCancerDataNetwork/oa-configurator
repo_name: oa-configurator

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: light-blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - footnotes
  - tables
  - attr_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - toc:
      permalink: true

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - js/mermaid-init.js

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
          options:
            show_source: false
            docstring_style: numpy
            merge_init_into_class: true
            separate_signature: true
            show_signature_annotations: true

nav:
  - Home: index.md
  - Getting Started: quickstart.md
  - Architecture: architecture.md

  - User Guide:
      - Config File Reference: config-reference.md
      - Secrets: secrets.md
      - Inline & Session Usage: inline-usage.md
      - Logging: logging.md
      - Integration: integration.md
  - API Reference:
      - Loader: api/loader.md
      - Stack Config: api/stack-config.md
      - Resources: api/resources.md
      - LLM: api/llm.md
      - Resolver: api/resolver.md
      - PackageConfigBase: api/package-base.md
      #- Persistence: api/persistence.md
      - Logging: api/logging.md