"""File I/O helpers: environment file export and TOML config persistence."""

from __future__ import annotations

import logging
import tomllib
from pathlib import Path
from typing import Any

import tomli_w

from .loader import DEFAULT_CONFIG_PATH
from .resolver import Resolver

logger = logging.getLogger(__name__)
FLAT_ENV_PATH = DEFAULT_CONFIG_PATH.parent / DEFAULT_CONFIG_PATH.stem.replace(".toml", ".env")


def write_env_file(resolver: Resolver, path: Path = FLAT_ENV_PATH) -> Path:
    """Write a flat KEY=VALUE file from the active resolved config.

    Written to *path* (default ``~/.config/omop/config.env``) for use with
    Docker Compose ``env_file:``.

    Naming convention
    -----------------
    - Resource ``<name>`` primary_db → ``<NAME>_DB_{HOST,PORT,USER,PASSWORD,NAME,DRIVER,URL}``
    - Tool ``<name>`` scalar extra fields → ``<NAME>_{KEY}``

    All resource names and tool names are uppercased with hyphens replaced by
    underscores.
    """
    lines: list[str] = [
        "# Generated by `omop-config export-env` — do not edit by hand.",
        "# Source of truth: ~/.config/omop/config.toml",
        "",
    ]

    for resource_name in resolver.config.resources:
        prefix = f"{resource_name.upper().replace('-', '_')}_DB"
        try:
            resolved = resolver.resolve_resource(resource_name)
            conn = resolver.effective_connection(resolved.primary_db.name)
        except Exception as exc:
            logger.warning("Skipping resource %r in env export: %s", resource_name, exc)
            continue

        if conn.host:
            lines.append(f"{prefix}_HOST={conn.host}")
        if conn.port:
            lines.append(f"{prefix}_PORT={conn.port}")
        if conn.user:
            lines.append(f"{prefix}_USER={conn.user}")
        if conn.password:
            lines.append(f"{prefix}_PASSWORD={conn.password}")
        if conn.database:
            lines.append(f"{prefix}_NAME={conn.database}")
        if conn.dialect:
            lines.append(f"{prefix}_DRIVER={conn.dialect}")
        lines.append(f"{prefix}_URL={resolved.primary_db.url}")
        lines.append("")

    for tool_name in resolver.config.tools:
        prefix = tool_name.upper().replace("-", "_")
        try:
            tool = resolver.resolve_tool(tool_name)
        except Exception as exc:
            logger.warning("Skipping tool %r in env export: %s", tool_name, exc)
            continue
        wrote_any = False
        for k, v in tool.extra.items():
            if isinstance(v, (str, int, float, bool)):
                lines.append(f"{prefix}_{k.upper()}={v}")
                wrote_any = True
        if wrote_any:
            lines.append("")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def save_stack_config(config: Any, path: Path = DEFAULT_CONFIG_PATH) -> Path:
    """Serialize a :class:`~oa_configurator.models.StackConfig` back to TOML.

    Does NOT preserve comments or original formatting. The ``logging`` section
    is omitted when it equals the default (no custom logging configured).
    """
    from .logging_config import LoggingConfig

    payload = _drop_none_and_empty(config.model_dump(mode="python"))
    if config.logging == LoggingConfig():
        payload.pop("logging", None)

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(tomli_w.dumps(payload), encoding="utf-8")
    return path


def patch_active_profile(profile_name: str, path: Path = DEFAULT_CONFIG_PATH) -> None:
    """Set ``active_profile`` in the TOML file without touching other fields.

    Creates the file with only ``active_profile`` if it does not exist.
    Used by ``omop-config use <profile>``.
    """
    data: dict[str, Any] = {}
    if path.exists():
        data = tomllib.loads(path.read_text(encoding="utf-8"))
    data["active_profile"] = profile_name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(tomli_w.dumps(data), encoding="utf-8")


def _drop_none_and_empty(value: Any) -> Any:
    """Recursively strip None values and empty dicts from a model_dump result."""
    if isinstance(value, dict):
        cleaned = {k: _drop_none_and_empty(v) for k, v in value.items() if v is not None}
        return {k: v for k, v in cleaned.items() if v != {}}
    if isinstance(value, list):
        return [_drop_none_and_empty(v) for v in value]
    return value
