blank_issues_enabled: false
contact_links:
  - name: ❓ Discussions
    url: https://github.com/AustralianCancerDataNetwork/oa-configurator/discussions
    about: Ask questions or start a general discussion.
